<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class EscolasTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('escolas')->delete();

        \DB::table('escolas')->insert([
            0 => [
                'id' => 1,
                'regiao' => 'Centro',
                'bairro' => 'Sumare',
                'name' => 'Adolfina Leonor Soares Dos Santos',
                'endereco' => 'Av. Siqueira Campos',
                'telefone' => '(12) 38812521',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            1 => [
                'id' => 2,
                'regiao' => 'Sul',
                'bairro' => 'Pereque Mirim',
                'name' => 'Adriana Aparecida Cassiano',
                'endereco' => 'R. Sao Roque',
                'telefone' => '(12) 38871449',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            2 => [
                'id' => 3,
                'regiao' => 'Centro',
                'bairro' => 'Rio Do Ouro',
                'name' => 'Aida de Almeida Castro Grazioli',
                'endereco' => 'Rua Francisco Ribeiro',
                'telefone' => '(12) 38822610',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            3 => [
                'id' => 4,
                'regiao' => 'Sul',
                'bairro' => 'Travessao',
                'name' => 'Alaor Xavier Junqueira',
                'endereco' => 'Rua Jose Ferreira Dos Santos',
                'telefone' => '(12) 38872612',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            4 => [
                'id' => 5,
                'regiao' => 'Norte',
                'bairro' => 'Massaguaçu',
                'name' => 'Antonia Antunes Arouca',
                'endereco' => 'Rua Italia Baffi Magni',
                'telefone' => '(12) 38843900',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            5 => [
                'id' => 6,
                'regiao' => 'Centro',
                'bairro' => 'Jardim California',
                'name' => 'Antonia Ribeiro Da Silva',
                'endereco' => 'Av. Cidade Alves Pereira',
                'telefone' => '(12) 38822286',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            6 => [
                'id' => 7,
                'regiao' => 'Centro',
                'bairro' => 'Estrela Dalva',
                'name' => 'Antonio De Freitas Avelar',
                'endereco' => 'Rua Joao Marcelo',
                'telefone' => '(12) 38822493',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            7 => [
                'id' => 8,
                'regiao' => 'Norte',
                'bairro' => 'Olaria',
                'name' => 'Aparecida Maria Pires De Meneses',
                'endereco' => 'Av. Marginal Ipiranga',
                'telefone' => '(12) 38838988',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            8 => [
                'id' => 9,
                'regiao' => 'Norte',
                'bairro' => 'Massagassu',
                'name' => 'Benedito Inacio Soares',
                'endereco' => 'Av Regina Margareth Passos',
                'telefone' => '(12) 38842450',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            9 => [
                'id' => 10,
                'regiao' => 'Centro',
                'bairro' => 'Rio Do Ouro',
                'name' => 'Bernardo Ferreira Louzada',
                'endereco' => 'Rua Horto Florestal',
                'telefone' => '(12) 38822221',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            10 => [
                'id' => 11,
                'regiao' => 'Sul',
                'bairro' => 'Morro Do Algodao',
                'name' => 'Carlos Altero Ortega',
                'endereco' => 'Rua Sete',
                'telefone' => '(12) 38873021',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            11 => [
                'id' => 12,
                'regiao' => 'Centro',
                'bairro' => 'Indaia',
                'name' => 'Carlos De Almeida Rodrigues Dr.',
                'endereco' => 'Av. Pernambuco',
                'telefone' => '(12) 38824679',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            12 => [
                'id' => 13,
                'regiao' => 'Centro',
                'bairro' => 'Poiares',
                'name' => 'Bairro Poiares',
                'endereco' => 'Av. Marechal Floriano Peixoto',
                'telefone' => '(12) 38876315',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            13 => [
                'id' => 14,
                'regiao' => 'Sul',
                'bairro' => 'Pereque Mirim',
                'name' => 'Celia Rocha Lobo',
                'endereco' => 'Rua Benedito Jacinto Do Prado',
                'telefone' => '(12) 38883311',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            14 => [
                'id' => 15,
                'regiao' => 'Sul',
                'bairro' => 'Tinga',
                'name' => 'Creche Santo Antonio',
                'endereco' => 'Rua Elvira Perpetua De Santana',
                'telefone' => '(12) 38873304',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            15 => [
                'id' => 16,
                'regiao' => 'Sul',
                'bairro' => 'Pereque Mirim',
                'name' => 'Edna Maria Nogueira Ferraz',
                'endereco' => 'Rua Benedito Fortunato',
                'telefone' => '(12) 38873014',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            16 => [
                'id' => 17,
                'regiao' => 'Sul',
                'bairro' => 'Barranco Alto',
                'name' => 'Elisa Butschkau',
                'endereco' => 'Avenida Manoel de Castro',
                'telefone' => '(12) 38871016',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            17 => [
                'id' => 18,
                'regiao' => 'Norte',
                'bairro' => 'Sertao Dos Tourinhos',
                'name' => 'Ester Nunes De Souza',
                'endereco' => 'Rua Manoel Francisco Ricardo',
                'telefone' => '(12) 38841655',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            18 => [
                'id' => 19,
                'regiao' => 'Sul',
                'bairro' => 'Pereque Mirim',
                'name' => 'Euclydes Ferreira',
                'endereco' => 'Av. Jose Geraldo Fernandes Da Silva Filho',
                'telefone' => '(12) 38851802',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            19 => [
                'id' => 20,
                'regiao' => 'Sul',
                'bairro' => 'Pereque Mirim',
                'name' => 'Francisco Assis De Carvalho',
                'endereco' => 'Av. Jose Geraldo Fernandes Da Silva Filho',
                'telefone' => '(12) 38851801',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            20 => [
                'id' => 21,
                'regiao' => 'Sul',
                'bairro' => 'Pereque Mirim',
                'name' => 'Geraldo De Lima',
                'endereco' => 'Av. Pedro Goncalves',
                'telefone' => '(12) 38874322',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            21 => [
                'id' => 22,
                'regiao' => 'Centro',
                'bairro' => 'Rio Do Ouro',
                'name' => 'Honorina Pacheco Correa',
                'endereco' => 'Av. Americo Thimoteo Do Rosario',
                'telefone' => '(12) 38835577',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            22 => [
                'id' => 23,
                'regiao' => 'Sul',
                'bairro' => 'Pereque Mirim',
                'name' => 'Jane Urbano Focesi',
                'endereco' => 'R. Sao Roque',
                'telefone' => '(12) 38871514',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            23 => [
                'id' => 24,
                'regiao' => 'Centro',
                'bairro' => 'Poiares',
                'name' => 'Joao Baptista Gardelin',
                'endereco' => 'Rua Joaquim Jose Da Silva Xavier',
                'telefone' => '(12) 38873101',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            24 => [
                'id' => 25,
                'regiao' => 'Sul',
                'bairro' => 'Baranco Alto',
                'name' => 'Joao Benedito Marcondes',
                'endereco' => 'Rua Benedito Severino De Castro',
                'telefone' => '(12) 38874291',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            25 => [
                'id' => 26,
                'regiao' => 'Sul',
                'bairro' => 'Baranco Alto',
                'name' => 'Joao Lino Da Cruz',
                'endereco' => 'Rua Luiz Jacinto Da Silva',
                'telefone' => '(12) 38882865',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            26 => [
                'id' => 27,
                'regiao' => 'Norte',
                'bairro' => 'Cantagalo',
                'name' => 'Joao Thimoteo Do Rosario',
                'endereco' => 'Estrada Do Cantagalo',
                'telefone' => '(12) 38890278',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            27 => [
                'id' => 28,
                'regiao' => 'Centro',
                'bairro' => 'Jaraguazinho',
                'name' => 'Jorge Passos',
                'endereco' => 'Rua Oziel Egidio De Faria',
                'telefone' => '(12) 38824395',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            28 => [
                'id' => 29,
                'regiao' => 'Sul',
                'bairro' => 'Travessao',
                'name' => 'Leonor Mendes De Barros',
                'endereco' => 'Rua Joao Carlos Balio',
                'telefone' => '(12) 38876108',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            29 => [
                'id' => 30,
                'regiao' => 'Centro',
                'bairro' => 'Tinga',
                'name' => 'Lucio Jacinto Dos Santos',
                'endereco' => 'Rua Denilza Sebastiana Santos',
                'telefone' => '(12) 38834533',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            30 => [
                'id' => 31,
                'regiao' => 'Centro',
                'bairro' => 'Martim De Sa',
                'name' => 'Luiz Ribeiro Muniz',
                'endereco' => 'Rua Analandia',
                'telefone' => '(12) 38825698',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            31 => [
                'id' => 32,
                'regiao' => 'Norte',
                'bairro' => 'Casa Branca',
                'name' => 'Luiz Silvar Do Prado',
                'endereco' => 'Rua Jose Pedro De Oliveira Barbosa',
                'telefone' => '(12) 38869931',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            32 => [
                'id' => 33,
                'regiao' => 'Centro',
                'bairro' => 'Tinga',
                'name' => 'Maria Aparecida De Carvalho',
                'endereco' => 'Av. Marechal Deodoro Da Fonseca',
                'telefone' => '(12) 38862050',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            33 => [
                'id' => 34,
                'regiao' => 'Sul',
                'bairro' => 'Porto Novo',
                'name' => 'Maria Aparecida Ujio',
                'endereco' => 'Av. Ezequiel Da Silva Barreto',
                'telefone' => '(12) 38873836',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            34 => [
                'id' => 35,
                'regiao' => 'Sul',
                'bairro' => 'Morro Do Algodao',
                'name' => 'Maria Carlita Saraiva Guedes',
                'endereco' => 'Travessa Cinco',
                'telefone' => '(12) 38883223',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            35 => [
                'id' => 36,
                'regiao' => 'Centro',
                'bairro' => 'Indaia',
                'name' => 'Maria De Lourdes Lucarelli Perez',
                'endereco' => 'Av. Santa Catarina',
                'telefone' => '(12) 38877822',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            36 => [
                'id' => 37,
                'regiao' => 'Centro',
                'bairro' => 'Tinga',
                'name' => 'Maria Elma Mansano',
                'endereco' => 'Av. Marechal Deodoro Da Fonseca',
                'telefone' => '(12) 38862054',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            37 => [
                'id' => 38,
                'regiao' => 'Norte',
                'bairro' => 'Casa Branca',
                'name' => 'Maria Eugenia Aranha Chodounsky',
                'endereco' => 'Rua Jose Pedro De Oliveira Barbosa',
                'telefone' => '(12) 38869932',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            38 => [
                'id' => 39,
                'regiao' => 'Centro',
                'bairro' => 'Jardim Gaivotas',
                'name' => 'Maria Moraes De Oliveira',
                'endereco' => 'Rua Pica Pau',
                'telefone' => '(12) 38877462',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            39 => [
                'id' => 40,
                'regiao' => 'Centro',
                'bairro' => 'Jaraguazinho',
                'name' => 'Maria Onicie Dias Pereira',
                'endereco' => 'Rua Jose Neder',
                'telefone' => '(12) 38878087',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            40 => [
                'id' => 41,
                'regiao' => 'Norte',
                'bairro' => 'Jetuba',
                'name' => 'Maria Thereza De Souza Castro',
                'endereco' => 'Rua Seishi Yoshimoto',
                'telefone' => '(12) 38842921',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            41 => [
                'id' => 42,
                'regiao' => 'Sul',
                'bairro' => 'Pegorelli',
                'name' => 'Masako Sone',
                'endereco' => 'Rua Abra De Dentro',
                'telefone' => '(12) 38872444',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            42 => [
                'id' => 43,
                'regiao' => 'Centro',
                'bairro' => 'Tinga',
                'name' => 'Meimei do Tinga',
                'endereco' => 'Rua Odete Machado Pinto',
                'telefone' => '(12) 38834648',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            43 => [
                'id' => 44,
                'regiao' => 'Centro',
                'bairro' => 'Ipiranga',
                'name' => 'Messias Mendes De Souza',
                'endereco' => 'Av. Brasil',
                'telefone' => '(12) 38839788',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            44 => [
                'id' => 45,
                'regiao' => 'Norte',
                'bairro' => 'Casa Branca',
                'name' => 'Oswaldo Ferreira',
                'endereco' => 'Rua Jose Pedro De Oliveira Barbosa',
                'telefone' => '(12) 38821067',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            45 => [
                'id' => 46,
                'regiao' => 'Norte',
                'bairro' => 'Tabatinga',
                'name' => 'Pedro Joao De Oliveira',
                'endereco' => 'Rua Benedito Serrado',
                'telefone' => '(12) 38842091',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            46 => [
                'id' => 47,
                'regiao' => 'Sul',
                'bairro' => 'Travessao',
                'name' => 'Regina Celia Santos Chapira Blaustein',
                'endereco' => 'Rua Jacupiranga',
                'telefone' => '(12) 38876422',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            47 => [
                'id' => 48,
                'regiao' => 'Sul',
                'bairro' => 'Praia Das Palmeiras',
                'name' => 'Ricardo Luques Sammarco Serra',
                'endereco' => 'Rua Aldo Marcucci',
                'telefone' => '(12) 38884186',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            48 => [
                'id' => 49,
                'regiao' => 'Centro',
                'bairro' => 'Estrela Dalva',
                'name' => 'Santina Nardi Marques',
                'endereco' => 'Rua Antonio Nardi',
                'telefone' => '(12) 38833477',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            49 => [
                'id' => 50,
                'regiao' => 'Centro',
                'bairro' => 'Jardim Das Gaivotas',
                'name' => 'Severino Vitoriano Dos Santos',
                'endereco' => 'Av. Cardeal',
                'telefone' => '(12) 38873047',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            50 => [
                'id' => 51,
                'regiao' => 'Centro',
                'bairro' => 'Tinga',
                'name' => 'Telma Do Amarante Veiga Santos',
                'endereco' => 'Rua Antonio Dos Santos',
                'telefone' => '(12) 38826090',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            51 => [
                'id' => 52,
                'regiao' => 'Sul',
                'bairro' => 'Porto Novo',
                'name' => 'Thereza Yanesse Schmidt Cardozo',
                'endereco' => 'Av. Ezequiel Da Silva Barreto',
                'telefone' => '(12) 38871565',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            52 => [
                'id' => 53,
                'regiao' => 'Norte',
                'bairro' => 'Jetuba',
                'name' => 'Vera Da Silva Santos',
                'endereco' => 'Av. Azaleias',
                'telefone' => '(12) 38893535',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            53 => [
                'id' => 54,
                'regiao' => 'Sul',
                'bairro' => 'Pereque Mirim',
                'name' => 'Yasutada Nasu',
                'endereco' => 'R. Pedro Goncalves Leite',
                'telefone' => '(12) 38874322',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            54 => [
                'id' => 55,
                'regiao' => 'Norte',
                'bairro' => 'Indaiá',
                'name' => 'Seduc',
                'endereco' => 'Av. Rio de Janeiro 860',
                'telefone' => '(12) 38977027',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            55 => [
                'id' => 56,
                'regiao' => 'Sul',
                'bairro' => 'Travessao',
                'name' => 'Stela da Silva',
                'endereco' => ' Rua João Carlos Balio, 355',
                'telefone' => '(12) 38977000',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            56 => [
                'id' => 57,
                'regiao' => 'Sul',
                'bairro' => 'Pegorelli',
                'name' => 'Waldete Ferreira de Souza',
                'endereco' => 'R. Circular, 10',
                'telefone' => '(12) 38977000',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            57 => [
                'id' => 58,
                'regiao' => 'Sul',
                'bairro' => 'Travessao',
                'name' => 'Debora Valle da Silva Pilon',
                'endereco' => 'Av. José da Costa Pinheiro Júnior, 422',
                'telefone' => '(12) 38878229',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            58 => [
                'id' => 59,
                'regiao' => 'Sul',
                'bairro' => 'Golfinho',
                'name' => 'Josiane Aparecida Ramos',
                'endereco' => 'Av. Emílio Manzano Lhorente, 670',
                'telefone' => '(12) 38977000',
                'status' => 1,
                'created_at' => '2023-03-21 16:45:37',
                'updated_at' => '2023-03-21 16:45:37',
            ],
            59 => [
                'id' => 60,
                'regiao' => 'Norte',
                'bairro' => 'Jetuba',
                'name' => 'Auracy Mansano',
                'endereco' => 'Rua Gabriel Fagundes da Rosa, 305.',
                'telefone' => '38977000',
                'status' => 1,
                'created_at' => '2023-03-21 16:45:37',
                'updated_at' => '2023-03-21 16:45:37',
            ],
            60 => [
                'id' => 61,
                'regiao' => 'Norte',
                'bairro' => 'Indaiá',
                'name' => 'Apoio - Seduc',
                'endereco' => 'Av. Rio de Janeiro 860',
                'telefone' => '(12) 38977027',
                'status' => 1,
                'created_at' => '2022-02-07 03:00:00',
                'updated_at' => '2022-02-07 03:00:00',
            ],
            61 => [
                'id' => 62,
                'regiao' => 'Centro',
                'bairro' => 'Centro',
                'name' => 'Centro',
                'endereco' => 'Rua Santos Dumont, 140',
                'telefone' => '(12) 38977027',
                'status' => 1,
                'created_at' => '2023-06-16 19:47:57',
                'updated_at' => '2023-06-16 19:47:57',
            ],
            62 => [
                'id' => 63,
                'regiao' => 'Centro',
                'bairro' => 'Sumare',
                'name' => 'Sumare',
                'endereco' => 'Av. Brasil, 1035',
                'telefone' => '(12) 38977027',
                'status' => 1,
                'created_at' => '2023-06-16 19:47:57',
                'updated_at' => '2023-06-16 19:47:57',
            ],
            63 => [
                'id' => 64,
                'regiao' => 'Centro',
                'bairro' => 'Jardim California',
                'name' => 'Jardim California',
                'endereco' => 'Rua Manoel do Amaral, 51',
                'telefone' => '(12) 38977027',
                'status' => 1,
                'created_at' => '2023-06-16 19:47:57',
                'updated_at' => '2023-06-16 19:47:57',
            ],
            64 => [
                'id' => 65,
                'regiao' => 'Sul',
                'bairro' => 'Morro do Algodão',
                'name' => 'Creche Meimei do Morro do Algodão',
                'endereco' => 'Rua Antonio Teles de Souza, 64',
                'telefone' => '(12) 38977027',
                'status' => 1,
                'created_at' => '2023-06-16 19:47:57',
                'updated_at' => '2023-06-16 19:47:57',
            ],
            65 => [
                'id' => 100,
                'regiao' => '',
                'bairro' => '',
                'name' => 'Outra escola',
                'endereco' => '',
                'telefone' => '',
                'status' => 1,
                'created_at' => '2023-03-21 16:45:37',
                'updated_at' => '2023-03-21 16:45:37',
            ],
        ]);

    }
}
