                    {{-- <x-ts-select.styled label="Escola" wire:model.live="form.escola_id"
                        :request="route('api.escolas')" select="label:name|value:id" /> --}}
@props([
    'label' => null,
    'campo' => null,
])

<x-ts-select.styled placeholder="Selecione.." label="{{ $label }}" wire:model.live="{{ $campo }}"
    select="label:label|value:value" :options="[
                        ['label' => 'Adolfina Leonor Soares Dos Santos', 'value' => 1],
                        ['label' => 'Adriana Aparecida Cassiano', 'value' => 2],
                        ['label' => 'Aida de Almeida Castro Grazioli', 'value' => 3],
                        ['label' => 'Alaor Xavier Junqueira', 'value' => 4],
                        ['label' => 'Antonia Antunes Arouca', 'value' => 5],
                        ['label' => 'Antonia Ribeiro Da Silva', 'value' => 6],
                        ['label' => 'Antonio De Freitas Avelar', 'value' => 7],
                        ['label' => 'Aparecida Maria Pires De Meneses', 'value' => 8],
                        ['label' => 'Benedito Inacio Soares', 'value' => 9],
                        ['label' => 'Bernardo Ferreira Louzada', 'value' => 10],
                        ['label' => 'Carlos Altero Ortega', 'value' => 11],
                        ['label' => 'Carlos De Almeida Rodrigues Dr.', 'value' => 12],
                        ['label' => 'Bairro Poiares', 'value' => 13],
                        ['label' => 'Celia Rocha Lobo', 'value' => 14],
                        ['label' => 'Creche Santo Antonio', 'value' => 15],
                        ['label' => 'Edna Maria Nogueira Ferraz', 'value' => 16],
                        ['label' => 'Elisa Butschkau', 'value' => 17],
                        ['label' => 'Ester Nunes De Souza', 'value' => 18],
                        ['label' => 'Euclydes Ferreira', 'value' => 19],
                        ['label' => 'Francisco Assis De Carvalho', 'value' => 20],
                        ['label' => 'Geraldo De Lima', 'value' => 21],
                        ['label' => 'Honorina Pacheco Correa', 'value' => 22],
                        ['label' => 'Jane Urbano Focesi', 'value' => 23],
                        ['label' => 'Joao Baptista Gardelin', 'value' => 24],
                        ['label' => 'Joao Benedito Marcondes', 'value' => 25],
                        ['label' => 'Joao Lino Da Cruz', 'value' => 26],
                        ['label' => 'Joao Thimoteo Do Rosario', 'value' => 27],
                        ['label' => 'Jorge Passos', 'value' => 28],
                        ['label' => 'Leonor Mendes De Barros', 'value' => 29],
                        ['label' => 'Lucio Jacinto Dos Santos', 'value' => 30],
                        ['label' => 'Luiz Ribeiro Muniz', 'value' => 31],
                        ['label' => 'Luiz Silvar Do Prado', 'value' => 32],
                        ['label' => 'Maria Aparecida De Carvalho', 'value' => 33],
                        ['label' => 'Maria Aparecida Ujio', 'value' => 34],
                        ['label' => 'Maria Carlita Saraiva Guedes', 'value' => 35],
                        ['label' => 'Maria De Lourdes Lucarelli Perez', 'value' => 36],
                        ['label' => 'Maria Elma Mansano', 'value' => 37],
                        ['label' => 'Maria Eugenia Aranha Chodounsky', 'value' => 38],
                        ['label' => 'Maria Moraes De Oliveira', 'value' => 39],
                        ['label' => 'Maria Onicie Dias Pereira', 'value' => 40],
                        ['label' => 'Maria Thereza De Souza Castro', 'value' => 41],
                        ['label' => 'Masako Sone', 'value' => 42],
                        ['label' => 'Meimei do Tinga', 'value' => 43],
                        ['label' => 'Messias Mendes De Souza', 'value' => 44],
                        ['label' => 'Oswaldo Ferreira', 'value' => 45],
                        ['label' => 'Pedro Joao De Oliveira', 'value' => 46],
                        ['label' => 'Regina Celia Santos Chapira Blaustein', 'value' => 47],
                        ['label' => 'Ricardo Luques Sammarco Serra', 'value' => 48],
                        ['label' => 'Santina Nardi Marques', 'value' => 49],
                        ['label' => 'Severino Vitoriano Dos Santos', 'value' => 50],
                        ['label' => 'Telma Do Amarante Veiga Santos', 'value' => 51],
                        ['label' => 'Thereza Yanesse Schmidt Cardozo', 'value' => 52],
                        ['label' => 'Vera Da Silva Santos', 'value' => 53],
                        ['label' => 'Yasutada Nasu', 'value' => 54],
                        ['label' => 'Seduc', 'value' => 55],
                        ['label' => 'Stela da Silva', 'value' => 56],
                        ['label' => 'Waldete Ferreira de Souza', 'value' => 57],
                        ['label' => 'Debora Valle da Silva Pilon', 'value' => 58],
                        ['label' => 'Josiane Aparecida Ramos', 'value' => 59],
                        ['label' => 'Auracy Mansano', 'value' => 60],
                        ['label' => 'Apoio - Seduc', 'value' => 61],
                        ['label' => 'Centro', 'value' => 62],
                        ['label' => 'Sumare', 'value' => 63],
                        ['label' => 'Jardim California', 'value' => 64],
                        ['label' => 'Creche Meimei do Morro do Algodão', 'value' => 65]
                    ]" />
